# Generated by Django 4.0 on 2021-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=34)),
                ('name', models.CharField(max_length=34)),
                ('father', models.IntegerField()),
                ('spec', models.IntegerField()),
            ],
        ),
    ]
