# Generated by Django 4.0 on 2021-12-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='icd',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
