# Generated by Django 4.0 on 2021-12-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_diseases_icd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='icd',
            new_name='ICD_10',
        ),
    ]
